on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python

  publish-pypi:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          environments: publish
          pixi-version: v0.42.1

      - name: Build source and wheel distribution + check build
        # this will build the source and wheel into the dist/ directory
        run: |
          pixi run --environment publish check-build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
